from __future__ import annotations

from typing import Any, Protocol


class BrowserContextLike(Protocol):
    def close(self) -> None: ...


class MouseLike(Protocol):
    def wheel(self, delta_x: float, delta_y: float) -> None: ...


class LocatorLike(Protocol):
    @property
    def first(self) -> "LocatorLike": ...

    def count(self) -> int: ...
    def nth(self, index: int) -> "LocatorLike": ...
    def inner_text(self, timeout: int = 0) -> str: ...
    def get_attribute(self, name: str) -> str | None: ...
    def scroll_into_view_if_needed(self, timeout: int = 0) -> None: ...
    def click(self, timeout: int = 0) -> None: ...


class CardLike(Protocol):
    def get_attribute(self, name: str) -> str | None: ...
    def scroll_into_view_if_needed(self, timeout: int = 0) -> None: ...


class PageLike(Protocol):
    @property
    def mouse(self) -> MouseLike: ...

    def locator(self, selector: str) -> LocatorLike: ...
    def wait_for_timeout(self, timeout: int) -> None: ...
    def wait_for_function(
        self,
        expression: str,
        arg: dict[str, int] | None = None,
        timeout: int = 0,
    ) -> Any: ...
    def wait_for_selector(self, selector: str, timeout: int = 0) -> LocatorLike: ...
    def screenshot(self, path: str | None = None, full_page: bool = False) -> Any: ...